### ISSUE TITLE
missing symlink to libblas.so

### ISSUE THREAD

**Issue by chi86** [gentoo-science/sci#703] opened 2016-11-29 07:40 UTC
Hi,
I had the issue, that octave is trying to find /usr/lib/libblas.so[.0/.3] and the same for liblapack.so, but the link from the libref* is missing and octave won't start. By creating this links by hand it works!
Shouldn't octave use the blas which is defined in eselect blas?

**Comment by marbre** [comment] 2016-11-29 08:37
If you selected blas/lapack from the science overlay, this replaces /usr/lib/libblas.so which is provided by blas-reference in the tree. Therefore, you have to recompile all applications using blas/lapack to get the executables linked to the new blas/lapack implementation. You cannot _dynamically_ switch the blas/lapack implementation with eselect, you always have to recompile afterwards.

**Comment by chi86** [comment] 2016-11-29 08:56
Yes that makes sence and I did that with octave but still it was looking for the old lib files! When starting octave I got a error message that it is missing the lib files and I would not start!

**Comment by marbre** [comment] 2016-11-29 09:04
The problem is that octave uses several libs that are linked against the old blas implentation. Therefore you have recompile these libs first. IMHO this is bug in octave's build system, but the maintainers don't see any problem with it, as reported [here](http://savannah.gnu.org/bugs/?42760) and [here](http://savannah.gnu.org/bugs/?49547).
Therefore, you need to recompile qrupdate and arpack prior to octave. It might be that additional libs need a recompile too, unfortunately I cannot check since I banned octave from my systems.

**Comment by chi86** [comment] 2016-11-29 09:07
Ok thanks I do that!

**Comment by kiwifb** [comment] 2016-11-29 09:07
octave pulls most of suitsparse and a few of them are using blas/lapack and should be recompiled.

**Comment by marbre** [comment] 2016-12-07 14:29
@chi86 Can we close this issue?

**Closed** 2016-12-07 14:44 UTC
